# Generated by Django 3.0.8 on 2020-08-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('Ganesh Steel Traders', 'Ganesh Steel Traders'), ('Ganesh Steel Corporation', 'Ganesh Steel Corporation')], default='Ganesh Steel Traders', max_length=30),
        ),
    ]
