# Generated by Django 3.1 on 2020-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_urlsdone_urlsleft'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
    ]
